#!/usr/bin/env bash
#
# Platform agnostic copy
#

if hash pbcopy 2>/dev/null; then
  pbcopy
elif hash xclip 2>/dev/null; then
  xclip -selection clipboard
elif hash putclip 2>/dev/null; then
  putclip
else
  rm -f /tmp/clipboard 2> /dev/null
  if [ $# -eq 0 ]; then
    cat > /tmp/clipboard
  else
    cat "$1" > /tmp/clipboard
  fi
fi

