#!/usr/bin/env zsh
#
# Refresh ZSH antidote plugins.
#

if [[ -z ${ANTIDOTE_STATIC_FILE} ]] || [[ -z ${ANTIDOTE_BUNDLE_FILE} ]]; then
  return
fi

[[ -f ${ANTIDOTE_STATIC_FILE} ]] && rm -rf ${ANTIDOTE_STATIC_FILE}
[[ -f ${ANTIDOTE_BUNDLE_FILE} ]] && rm -rf ${ANTIDOTE_BUNDLE_FILE}

# Ensure `plugins.antidote` is always first!
cat ${ZDOTDIR}/plugins/plugins.antidote > ${ANTIDOTE_BUNDLE_FILE}
for zplugin in ${ZDOTDIR}/plugins/*/*.antidote; do
  cat ${zplugin} >> ${ANTIDOTE_BUNDLE_FILE}
done
cat ${ZDOTDIR}/plugins/last-plugins.antidote >> ${ANTIDOTE_BUNDLE_FILE}
unset zplugin
antidote bundle < ${ANTIDOTE_BUNDLE_FILE} > ${ANTIDOTE_STATIC_FILE}

