#!/usr/bin/env zsh
#
# Refresh ZSH home-manager session vars to force having latest value of the env
# variables.
#

[[ -r ${HOME}/.nix-profile/etc/profile.d/hm-session-vars.sh ]] && unset __HM_SESS_VARS_SOURCED && source ${HOME}/.nix-profile/etc/profile.d/hm-session-vars.sh

# vim: ft=zsh
