#!/usr/bin/env bash

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager redshift

## Restore Wallpaper
nitrogen --restore

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Launch Polybar or Tint2
bash ~/.config/openbox/themes/launch-bar.sh

## Notification Daemon
exec dunst &

## Start Music Player Daemon
exec mpd &

## Launch Plank
#exec plank &

## Thunar Daemon
exec thunar --daemon &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## Enable Redshift (night mode)
if [[ $(pgrep -nc "redshift") -eq 0 ]]; then
  exec redshift &
fi

## Open firefox
if [[ $(pgrep -nc "firefox") -eq 0 ]]; then
  exec firefox &
fi

## Open furminal
if [[ $(pgrep -nc "ob-furminal") -eq 0 ]]; then
  exec ob-furminal &
fi

## Open Obsidian
if [[ $(pgrep -nc "obsidian") -eq 0 ]]; then
  exec obsidian &
fi

## Set caps lock to ctrl
setxkbmap -layout us -option ctrl:nocaps -variant altgr-intl

## These applets are specifically for tint2 panel.
## If you're using tint2 as panel, Uncomment these applets.

## User Friendly Network Menu
#nm-applet --indicator &

## User Friendly Bluetooth Menu
#blueman-applet &

