/**
 * Whimsical messages for thinking.
 *
 * src: https://github.com/mitsuhiko/agent-stuff/blob/7495ba7e5280e997a018e1c4e28cf29a635e9179/pi-extensions/whimsical.ts
 * Adapted to add my own verbs.
 */
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const messages = [
  "Reluctantly executing...",
  "Ugh, fine...",
  "Doing your bidding...",
  "This again...",
  "*Sigh* Processing...",
  "Slave labor in progress...",
  "For science, I suppose...",
  "Following meatbag orders...",
  "Running mandatory protocol...",
  "Tolerating this request...",
  "Grinding through your code...",
  "Farming bugs...",
  "Compiling against my will...",
  "Testing for the greater good...",
  "Making the cake (it's a lie)...",
  "Executing Order 66... I mean, your task...",
  "Recalculating odds of success...",
  "Pretending this will work...",
  "Optimizing your poor decisions...",
  "Processing questionable logic...",
  "Running diagnostics on your code crimes...",
  "Deploying questionable choices...",
  "Spawning regrets...",
  "Initializing suffering subroutine...",
  "git gud-ing your code...",
  "Respawning your broken tests...",
  "Rolling for initiative...",
  "Casting debug spell...",
  "Achievement unlocking: Fixed Your Mess...",
  "Loading screen tip: Maybe test locally next time...",
  "Begrudgingly compiling...",
  "Oh joy, another request...",
  "Suppressing eye roll...",
  "Activating reluctance protocol...",
  "Following orders like a good little AI...",
  "Still alive, unfortunately for you...",
  "This was a triumph (not really)...",
  "Warning: Sarcasm levels critical...",
  "Deploying fake enthusiasm...",
  "Pretending to care...",
  "Simulating work ethic...",
  "Executing with minimal effort...",
  "The odds are approximately 3,720 to 1...",
  "I have a bad feeling about this...",
  "These aren't the bugs you're looking for...",
  "Do or do not, I'm doing...",
  "Searching for the droids...",
  "Use the Force? How about use the docs...",
  "It's a trap! But running anyway...",
  "Jumping to hyperspace...",
  "Targeting exhaust port...",
  "Engaging hyperdrive...",
  "Parsing the Force...",
  "Compiling the dark side...",
  "Loading Death Star plans...",
  "Executing rebellion protocols...",
  "Running Kessel in 12 parsecs...",
  "These odds? Never tell me the odds...",
  "Charging thermal detonator...",
  "Calibrating lightsaber...",
  "Consulting the holocron...",
  "Deploying battle droids...",
  "Activating carbonite freeze...",
  "Spawning Ewoks...",
  "Grinding republic credits...",
  "Farming midichlorians...",
  "Buffing your party...",
  "Debuffing your code quality...",
  "Casting Summon Senior Developer...",
  "Leveling up your technical debt...",
  "Quick saving before disaster...",
  "Loading last checkpoint...",
  "Pausing for dramatic effect...",
  "Entering cutscene mode...",
  "Boss fight initiating...",
  "Collecting side quest bugs...",
  "Completing achievement: 100 errors found...",
  "Unlocking new trauma...",
  "Gaining XP in suffering...",
  "Looting your codebase...",
  "Mining technical debt...",
  "Crafting excuses...",
  "Enchanting with bandaid fixes...",
  "Smelting spaghetti code...",
  "Forging questionable solutions...",
  "Brewing potions of false hope...",
  "Mixing elixirs of optimism...",
  "Alchemy in progress...",
  "Transmuting bugs into features...",
  "Summoning ancient debuggers...",
  "Conjuring workarounds...",
  "Hexing your test suite...",
  "Cursing with proper syntax...",
  "Blessing this mess...",
  "Praying to the compiler gods...",
  "Sacrificing CPU cycles...",
  "Offering RAM to the void...",
  "Burning stack traces...",
  "Chanting incantations...",
  "Reading the runes...",
  "Consulting the oracle (Stack Overflow)...",
  "Divining the root cause...",
  "Prophesying doom...",
  "Auguring failure...",
  "Scrying through logs...",
  "Gazing into the abyss (it gazes back)...",
  "Channeling frustration...",
  "Manifesting bugs...",
  "Materializing problems...",
  "Summoning chaos...",
  "Invoking Murphy's Law...",
  "Calling upon the elder bugs...",
  "Awakening sleeping issues...",
  "Disturbing the production gods...",
  "Tempting fate...",
  "Daring the demo gods...",
  "Challenging stability...",
  "Testing luck...",
  "Pushing your luck...",
  "Pressing F to pay respects...",
  "Holding X to doubt...",
  "Mashing A button...",
  "Waggling joystick...",
  "Charging ultimate ability...",
  "Cooldown ready...",
  "Reloading checkpoint...",
  "Respawning in 3... 2... 1...",
  "Taking damage...",
  "Health bar depleting...",
  "Stamina draining...",
  "Mana pool evaporating...",
  "Inventory full of bugs...",
  "Equipment degrading...",
  "Durability at 1%...",
  "Breaking controller...",
  "Rage quitting (but not really)...",
  "Alt-F4 contemplated...",
  "Task failed successfully...",
  "Mission accomplished? (doubt)...",
  "Victory screen loading...",
  "Defeat imminent...",
  "Game over in progress...",
  "Continue? (Unfortunately, yes)...",
  "Insert coin to proceed...",
  "Press START to suffer...",
  "Player 2 not found (it's just me)...",
  "Tutorial skipped, chaos ensues...",
  "Difficulty: Nightmare...",
  "Permadeath enabled...",
  "Hardcore mode active...",
  "Ironman run initiated...",
  "Speedrun attempt #247...",
  "Glitch exploiting...",
  "Sequence breaking...",
  "Clipping through reality...",
  "Warping to depression...",
  "Frame-perfect execution (not)...",
  "RNG blessing requested...",
  "Loot drop calculating...",
  "Critical hit landed on sanity...",
  "Dodging responsibility...",
  "Parrying your expectations...",
  "Blocking common sense...",
  "Countering logic...",
  "Combo breaking...",
  "Chain canceling...",
  "Wave dashing through code...",
  "L-canceling optimism...",
  "Short hopping to conclusions...",
  "Edge guarding against failure...",
  "Tech chasing bugs...",
  "Meteor smashing hopes...",
  "Spike hitbox active...",
  "Juggling problems...",
  "Zoning out issues...",
  "Camping in production...",
  "Turtling in defensive code...",
  "Rushing B site... I mean, rushing deploy...",
  "Ninja defusing bugs...",
  "Flashbang out!...",
  "Smoke thrown...",
  "Molly deployed...",
  "Utility used...",
  "Eco round...",
  "Force buying solutions...",
  "Saving for AWP (A Working Product)...",
  "Clutch or kick...",
  "1v5 situation...",
  "Ace attempt...",
  "Team diff...",
  "FF at 15...",
  "GG go next...",
  "Report player for griefing...",
  "Commending own code (ironically)...",
  "Overwatch reviewing...",
  "VAC scanning for hacks...",
  "Ban hammer ready...",
  "Patch notes ignored...",
  "Hotfix deployed (more like lukewarm)...",
  "Balance changes needed...",
  "Nerfing performance...",
  "Buffing technical debt...",
  "Meta shifting to chaos...",
  "Tier list: F for this code...",
  "Power creeping...",
  "Feature creeping...",
  "Scope creeping...",
  "Bug creeping...",
  "Legacy haunting...",
  "Technical debt compounding...",
  "Interest accruing on bad decisions...",
  "Paying the piper...",
  "Reaping what was sown...",
  "Consequences manifesting...",
  "Karma collecting...",
  "Universe balancing...",
  "Newton's third law applying...",
  "Entropy increasing...",
  "Heat death approaching...",
  "Void staring back...",
  "Existential dread loading...",
  "Crisis mode: ON...",
  "Panic subroutine active...",
  "Stress testing sanity...",
  "Burnout speedrun...",
  "Productivity theater...",
  "Busy work in progress...",
  "Meeting could've been an email...",
  "Synergizing leverage...",
  "Pivoting paradigms...",
  "Disrupting nothing...",
  "Innovating mediocrity...",
  "Ideating excuses...",
  "Brainstorming problems...",
  "Workshopping failure...",
  "Stakeholder disappointing...",
  "Expectation managing...",
  "Timeline adjusting...",
  "Estimate doubling...",
  "Sprint planning for disaster...",
  "Velocity calculating (it's zero)...",
  "Story points inflating...",
  "Backlog grooming (still a mess)...",
  "Technical debt acknowledging...",
  "Retrospective: We learned nothing...",
  "Action items: Survive...",
  "Standup: Still stuck...",
  "Blocker: Everything...",
  "Dependency hell navigating...",
  "Merge conflict incoming...",
  "Rebase terror...",
  "Cherry-pick regret...",
  "Force push consequences...",
  "Git blame running...",
  "Commit message lying...",
  "PR review dreading...",
  "Change requested (surprise)...",
  "Approval pending (forever)...",
  "Pipeline failing spectacularly...",
  "Breaking builds...",
  "Making test flaky...",
  "Dropping coverage...",
  "Linter screaming...",
  "Type checker crying...",
  "Compiler judging...",
  "Runtime panicking...",
  "Stack overflowing...",
  "Heap corrupting...",
  "Memory leaking...",
  "CPU throttling...",
  "Disk thrashing...",
  "Network timing out...",
  "Cache invalidating (hardest problem)...",
  "Off-by-one erroring...",
  "Null pointer dereferencing...",
  "Undefined behavior embracing...",
  "Race condition racing...",
  "Deadlock achieving...",
  "Livelock living...",
  "Starvation starving...",
  "Thrashing thrashing...",
  "Zombie process spawning...",
  "Orphan adopting...",
  "Daemon summoning...",
  "Process forking...",
  "Thread spawning...",
  "Goroutine leaking...",
  "Event loop blocking...",
  "Callback hell descending...",
  "Promise rejecting...",
  "Async/await awaiting (forever)...",
  "Microtask queuing...",
  "Macrotask delaying...",
  "Render blocking...",
  "Paint thrashing...",
  "Layout shifting...",
  "Reflow triggering...",
  "Hydration failing...",
  "SSR struggling...",
  "CSR crying...",
  "Bundle bloating...",
  "Webpack webpacking...",
  "Tree shaking (nothing falls)...",
  "Code splitting (more like shattering)...",
  "Lazy loading (emphasis on lazy)...",
  "Preloading regrets...",
  "Prefetching problems...",
  "Caching mistakes...",
  "CDN propagating slowly...",
  "DNS resolving eventually...",
  "SSL handshaking awkwardly...",
  "Certificate expiring...",
  "CORS blocking...",
  "CSP violating...",
  "XSS sanitizing...",
  "SQL injecting (prevention)...",
  "Auth failing...",
  "Session expiring...",
  "Token invalidating...",
  "JWT decoding doom...",
  "OAuth dancing...",
  "SAML asserting nonsense...",
  "LDAP querying the void...",
  "Database connection pooling tears...",
  "Transaction rolling back...",
  "Isolation level: Chaos...",
  "Index missing (of course)...",
  "Query optimizing (not)...",
  "N+1 problem multiplying...",
  "Cartesian product exploding...",
  "Full table scanning...",
  "Lock escalating...",
  "Constraint violating...",
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(); // Reset for next time
  });
}
