#!/usr/bin/env bash
#
#MISE description="Update all"
#

set -eu

if type mise >/dev/null 2>&1; then
  echo "> Updating tools installed from mise"
  mise up
fi

if type brew >/dev/null 2>&1; then
  echo "> Updating tools installed from homebrew"
  brew upgrade
fi

mise run update:mise
mise run update:brew
mise run update:flake
mise run home:apply
