#!/usr/bin/env bash
#
#MISE description="Update all"
#

set -eu

if type brew >/dev/null 2>&1; then
  echo "> Updating tools installed from homebrew"
  brew upgrade
else
  echo "> homebrew not installed" >&2
fi
