#!/usr/bin/env bash

rm -rf "${HOME}/.cache/nvim-pack"
rm -rf "${HOME}/.local/state/nvim-pack"
rm -rf "${HOME}/.local/share/nvim-pack"
rm -f "${HOME}/.config/nvim-pack/nvim-pack-lock.json"
echo "Cleaned Neovim cache, state, lock-file, and data directories"
