#!/bin/bash


get_all_used_swap() {
  for i in /proc/*/status ; do
    local vmswap=$(cat $i | grep "^VmSwap" 2>/dev/null)
    if [ $? == 0 ] && [ "${vmswap}" != "" ] ; then
      local pid=$(echo $i | awk -F'/' '{ print $3 }')
      local process=$(get_process_command ${pid})
      local used_swap_in_kb=$(echo ${vmswap} | awk '{ print $2 }')

      printf '%10s %-30.30s %10s kB\n' ${pid} ${process} ${used_swap_in_kb}
    fi
  done
}

get_process_command() {
  local pid=$1
  ps aux | grep "${pid}" | awk "\$2 == ${pid} { print \$11 }"
}

get_all_used_swap | sort -k3 -n | fzf --border --tac | awk '{ print $1 }' | xargs kill

