#!/usr/bin/env zsh
#
# Extract the jira ticket from the branch name and open it in the browser.
# Branch names look like: FEATURE-1234-description-of-feature.
#

red='\e[1;30;41m'
escape='\e[0m'

error() {
  >&2 echo -e "${red} E ${escape} ${1}"
}

if !type git &>/dev/null; then
  error "git is not installed"
  return
fi
if !type jira &>/dev/null; then
  error "jira cli is not installed"
  return
fi

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
JIRA_TICKET=$(echo "${BRANCH_NAME}" | grep -oE '[A-Z0-9]+-[0-9]+' || true)

if [[ -z "${JIRA_TICKET}" ]]; then
  error "No jira ticket found in branch name: $BRANCH_NAME"
  return
fi

jira open "${JIRA_TICKET}"
return
