[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"
# In a special situation (alacritty -> tmux -> zsh), for some reason, this
# FZF_DEFAULT_OPTS env variable is not updated for some tools, like
# https://github.com/wfxr/tmux-fzf-url, and overriding it with alacritty
# will "trigger" the update...
# In other situations, e.g. alacritty -> zsh or even alacritty -> zsh -> tmux,
# this env variable is correctly updated...
FZF_DEFAULT_OPTS = ""

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12

[shell]
program = "tmux"
args = ["-2", "-u"]
