#!/usr/bin/env bash
#
#MISE description="Task to run after a MacOS reboot/startup"
#

mise run home:apply
mise run darwin:update
unleash-the-keys

# Launch notes cron tasks.
if [ -d "$HOME/perso/codeberg/notes" ]; then
  cd "$HOME/perso/codeberg/notes"
  mise run auto-commit:restart
  mise run waypoint:restart
fi
