#!/usr/bin/env bash
#
#MISE description="Update Nix flake lock file"
#USAGE flag "-i --input <input>" help="Flake to update (default: all)" default="all"
#

if [[ "${input}" == "all" ]]; then
  echo "> Updating Nix flake lock file..."
  nix flake update
else
  echo "> Updating Nix flake ${input}..."
  nix flake update ${input}
fi
