require("config.colorscheme")
require("config.filetypes")
require("config.options")
require("config.autocmds")
require("config.keymaps")
require("config.statusline")
require("config.lsp")
require("plugins")
