#!/usr/bin/env zsh
#
# remove merged branches
# src: https://stackoverflow.com/questions/6127328/how-do-i-delete-all-git-branches-which-have-been-merged
#

git branch --merged | grep -Ev "(^\*|^\+|master|main|dev)" | xargs --no-run-if-empty git branch -D
