[display]
repository_style = "name"

[story_review]
agent_command = ["pi", "--models", "unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q4_K_M", "--no-session", "-p", "@{{prompt_file}}"]

[keymaps.global]
open_actions_popup = "alt+a"

[keymaps.actions_popup]
submit_selected_picker = ["alt+enter", "ctrl+s"]

[keymaps.pull_requests]
comment_on_pull_request = "alt+c"
