[tools]
# Agentic coding tool that lives in your terminal: https://github.com/anthropics/claude-code
"npm:@anthropic-ai/claude-code" = "1.0.35"
# A CLI tool for analyzing Claude Code usage from local JSONL files: https://github.com/ryoppippi/ccusage
"npm:ccusage" = "15.2.0"
