#!/usr/bin/env bash
#
#MISE description="Switch polarity from dark to light or vice versa"
#

set -euo pipefail

DEFAULT_THEME_DARK='kanagawa'
DEFAULT_THEME_LIGHT='kanagawa-lotus'

current_theme=$(grep 'theme = ' flake.nix | cut -d'"' -f2 | tr -d ' ')

if [[ "${DEFAULT_THEME_LIGHT}" == "${current_theme}" ]]; then 
  mise run colorscheme:change "${DEFAULT_THEME_DARK}"
  mise run colorscheme:change-macos-polarity true
else
  mise run colorscheme:change "${DEFAULT_THEME_LIGHT}"
  mise run colorscheme:change-macos-polarity false
fi
