GOOSE_CLI_THEME: ansi
GOOSE_MODE: approve
GOOSE_PROVIDER: anthropic
# Models available in the source code: https://github.com/block/goose/blob/97a0c529f22e8bf5f6abbe121085dedbbd35c02c/crates/goose/src/providers/anthropic.rs#L17-L27
GOOSE_MODEL: claude-sonnet-4-20250514
ANTHROPIC_HOST: https://api.anthropic.com
extensions:
  developer:
    bundled: null
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  knowledgegraphextension:
    args:
    - run
    - -i
    - -v
    - goose-memory:/app/dist
    - --rm
    - mcp/memory
    bundled: null
    cmd: docker
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: Knowledge Graph Extension
    timeout: 300
    type: stdio
  memory:
    bundled: null
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
  tutorial:
    bundled: null
    display_name: Tutorial
    enabled: false
    name: tutorial
    timeout: 300
    type: builtin
