#!/usr/bin/env zsh
#
# remove merged branches
# src:
# - https://stackoverflow.com/questions/6127328/how-do-i-delete-all-git-branches-which-have-been-merged
# - https://spencer.wtf/2026/02/20/cleaning-up-merged-git-branches-a-one-liner-from-the-cias-leaked-dev-docs.html
#

git branch --merged | grep -vE "^\s*(\*|main|master)" | xargs -n 1 --no-run-if-empty git branch -d
