#!/usr/bin/env zsh
#
# Refresh FZF_DEFAULT_OPTS, so that the current session has updated fzf options.
# Used especially to have updated colors.
#

if [ -f "${ZDOTDIR:-${HOME}/.config/zsh}/zprofile.d/.zprofile.fzf" ]; then
  source "${ZDOTDIR:-${HOME}/.config/zsh}/zprofile.d/.zprofile.fzf"
fi

