#!/usr/bin/env bash
#
#MISE description="Configure colima to work with testcontainers"
#src: https://golang.testcontainers.org/system_requirements/using_colima/
#

set -eu

echo "> Creating symbolink link from Docker socket"
sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
echo "> Restarting colima"
colima stop
colima start --network-address
