#!/usr/bin/env zsh
#
# Simple script that get quick answer from the command line.
# It's using the `direct-answer-engine` system prompt to generate the short answer.
# inspired from: https://github.com/kagisearch/ask
#

red='\e[1;30;41m'
escape='\e[0m'

error() {
  >&2 echo -e "${red} E ${escape} ${1}"
}

if !type -q pi &>/dev/null; then
  error "pi not installed"
  return
fi

pi --model 'llama-cpp/ornith1.0' -p "/direct-answer $@"
return
