"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[opener]
edit = [
	{ run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
edit-doc = [
	{ run = 'soffice "$@"', desc = "Edit with Libre Office", for = "unix" },
]
edit-image = [
	{ run = 'gimp "$@"', desc = "Edit image", for = "unix" },
]
open-image = [
	{ run = 'imv "$@"', desc = "Open image", for = "unix" },
]
open-pdf = [
	{ run = 'zathura "$@"', desc = "Open PDF", for = "unix" },
]

[[open.prepend_rules]]
mime = "image/*"
use = [ "open-image", "edit-image", "reveal" ]

[[open.prepend_rules]]
mime = "application/pdf"
use = [ "open-pdf", "open", "reveal" ]

[[open.prepend_rules]]
mime = "application/oasis.opendocument.*"
use = [ "edit-doc", "open", "reveal" ]

