#!/usr/bin/env bash

rm -rf "${HOME}/.cache/nvim"
rm -rf "${HOME}/.local/state/nvim"
rm -rf "${HOME}/.local/share/nvim"
rm -f "${HOME}/.config/nvim/nvim-pack-lock.json"
echo "Cleaned Neovim cache, state, lock-file, and data directories"
